### ISSUE TITLE
ERROR:root:Could not find any typelib for Caja

### ISSUE THREAD

**Issue by Hypfer** [mate-desktop/python-caja#16]
ERROR:root:Could not find any typelib for Caja
ImportError: No module named Caja

(caja:6515): Caja-Python-WARNING **: caja_python_init_python failed

Version is 1.8.0-0+wheezy

sudo apt-get install gir1.2-caja

is NOT the solution.

**Comment by monsta** [comment]
The original issue doesn't happen anymore. For "another relevant problem", there are patches in various distros.
