### ISSUE TITLE
Make python-caja cross-compile safe

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/python-caja#28]
plus some autoconf hygiene (AS_IF clauses):
https://anonscm.debian.org/cgit/pkg-mate/python-caja.git/tree/debian/patches/1001_pkg-config-macro-not-cross-compilation-safe.patch?id=7b54969a354e92d94052acb80a08dce586d42aca

**Comment by raveit65** [comment]
Link gives me 404 !

**Comment by raveit65** [comment]
```
-dnl Check for pkgconfig first
-AC_CHECK_PROG(HAVE_PKGCONFIG, pkg-config, yes, no)
-AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
-
+PKG_PROG_PKG_CONFIG
```
This is OK, the other changes i don't know.

**Comment by sunweaver** [comment]
Hi,

On Saturday, 12 January 2019, raveit65 wrote:
> ```
> -dnl Check for pkgconfig first
> -AC_CHECK_PROG(HAVE_PKGCONFIG, pkg-config, yes, no)
> -AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
> -
> +PKG_PROG_PKG_CONFIG
> ```
> This is OK, the other changes i don't know.
> 

We also need the bits that then use $PKG_CONFIG. The lower part of the patch is AS_IF hygiene.

I'll file a PR later...

Mike

-- 
Sent from my Sailfish device

**Comment by monsta** [comment]
This is fixed in master as https://github.com/mate-desktop/python-caja/pull/49 is merged.
