### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by carlwgeorge** [mate-desktop/python-caja#30]
Is this software compatible with Python 3?  The README file says that Python 2.7 is required, but it isn't clear if that's a minimum requirement or if Python 2.7.x is needed.

If the software is compatible with Python 3, is it possible to install two versions at the same time, one linked against Python 2 and the other against Python 3?  Perhaps by switching from:

- /usr/lib64/caja/extensions-2.0/libcaja-python.so

to:

- /usr/lib64/caja/extensions-2.0/libcaja-python2.so
- /usr/lib64/caja/extensions-2.0/libcaja-python3.so

**Comment by raveit65** [comment]
Yes, it builds fine against python3.
We did that already in fedora.
https://src.fedoraproject.org/cgit/rpms/python-caja.git/commit/?id=f3492ef86c0c6d82760976542984f1f7390c8950

**Comment by monnerat** [comment]
Well... it builds against python3, but there are problems at run-time: `PyString_*` functions have disappeared in python3 and I can see errors like (fedora 29 64-bit):
`** (caja:4649): WARNING **: 19:59:44.100: /usr/lib64/caja/extensions-2.0/libcaja-python.so: undefined symbol: PyString_AsString`
This is reported as a warning, but I guess it renders the library unusable.
I found it while investigating why rabbitvcs-caja is not showing in caja menus: maybe this is the reason, I have to check further.
It seems all python3 strings are unicode: I found that by googling: https://mail.python.org/pipermail/python-list/2009-March/527813.html

**Comment by encukou** [comment]
Hello,
May I shamelessly suggest an open [guide](https://py3c.readthedocs.io/en/latest/guide-porting.html) and [compat header](https://github.com/encukou/py3c/blob/master/include/py3c/compat.h) for handling the bytes/unicode split in C extensions?

I don't use caja (and I don't see automatic tests I could run), so I'm not the best person to do the porting, but I can help if you have any Python-related questions.

**Comment by monsta** [comment]
#34 and #35 are merged, so this project now has Python 3 compatibility (while still being compatible with Python 2).
